language: python
python:
  - "3.4"
  - "3.5"

script: python -m unittest
notifications:
  slack:
    secure: EcmPexVs9KY2A2A/yhgK01y0SJP843EcsN86E24GkSdPpYYYzBUXWChwDMHJ/ceMlt5em63jw5ntj2XMfW2w72lS7f8fKRRv6K2kSALGWq2DiDTwGAIwMMdHyBCbC45wA0JVuTbpMtK6FWIu6YGVMdXRxjjQfNfor0NyQH9GO0liy5Y5v4041o1oNI2D2V69pw+pX6vL8dqols4R4uOacuLjk/G0xfleqqeTh+tAecyK6+vEa235JmaSX0vK/9wXTnqMTy7uZXpuGE7h4xjQlkwiNOEvJzh+puYFwD1TjGIra8YabXpD0pGUgNwUZxgxrJ+T9NoMNXyaRmltiOYynkrw2PqD7m4Ul/gMu0N24R9ckDhvftmUm0fphOBqIMaO6ARYmmBd75dwZ3I3Xq3WxquAIY5M4ODjpnnydjzxw+b2xYBgX74XIlI1MY4Xd1HbkPtxzHrsN9SJRMD8zXNS+oIWJkyS3oqiBNpwZwhgMmLJmx7ZV1GKapFV5fRQ505tKPXtAKh3fda6OiUTbxPNNl4xaepg1288dLKAxLuZKFPqrtWOK8DMEyCJ3Ce+zHpagaMgxomAF+mb9F1LLT9TKbHQY91DGb29ILsh6BBKLzpt2Qw4FsnaJ8QP+6DyMBh5IGOE7DywfcGrz17fCI01bg+XmMRC+g/Fv9kRmvRhEqU=

